$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$code = @'
using System;using System.IO;using System.Drawing;using System.Drawing.Imaging;using System.Collections.Generic;
public static class EquipmentV1 {
 static string root; static Color[] p; static Dictionary<string,Bitmap> a=new Dictionary<string,Bitmap>(); static List<string> report=new List<string>();
 static Bitmap New(int w,int h){return new Bitmap(w,h,PixelFormat.Format32bppArgb);}
 static void Check(bool b,string m){if(!b)throw new Exception(m);}
 static Rectangle Bounds(Bitmap b){int l=b.Width,t=b.Height,r=-1,d=-1;for(int y=0;y<b.Height;y++)for(int x=0;x<b.Width;x++)if(b.GetPixel(x,y).A>=128){l=Math.Min(l,x);t=Math.Min(t,y);r=Math.Max(r,x);d=Math.Max(d,y);}return Rectangle.FromLTRB(l,t,r+1,d+1);}
 static int Near(Color c){int best=int.MaxValue,n=0;for(int i=0;i<p.Length;i++){if(i==25)continue;int d=(c.R-p[i].R)*(c.R-p[i].R)+(c.G-p[i].G)*(c.G-p[i].G)+(c.B-p[i].B)*(c.B-p[i].B);if(d<best){best=d;n=i;}}return n;}
 static bool Cyan(Color c){return c.A!=0&&Near(c)>=18&&Near(c)<=21;}
 static void Put(Bitmap d,Bitmap s,int x,int y){for(int j=0;j<s.Height;j++)for(int i=0;i<s.Width;i++){if(x+i<0||y+j<0||x+i>=d.Width||y+j>=d.Height)continue;Color c=s.GetPixel(i,j);if(c.A==0)continue;if(c.A==255)d.SetPixel(x+i,y+j,c);else{Color z=d.GetPixel(x+i,y+j);int al=c.A;d.SetPixel(x+i,y+j,Color.FromArgb(255,(c.R*al+z.R*(255-al)+127)/255,(c.G*al+z.G*(255-al)+127)/255,(c.B*al+z.B*(255-al)+127)/255));}}}
 static void Up(Bitmap b,string name,int k){using(var d=New(b.Width*k,b.Height*k)){for(int y=0;y<d.Height;y++)for(int x=0;x<d.Width;x++)d.SetPixel(x,y,b.GetPixel(x/k,y/k));d.Save(Path.Combine(root,name+".png"),ImageFormat.Png);}}
 static void Save(string n,Bitmap b){a.Add(n,b);b.Save(Path.Combine(root,n+".png"),ImageFormat.Png);Up(b,n+"_8x",8);}
 static Bitmap Reduce(string name,int k){using(var s=new Bitmap(Path.Combine(root,"sources/"+name+"_generated.png"))){var r=Bounds(s);var b=New((r.Width+k-1)/k,(r.Height+k-1)/k);for(int y=0;y<b.Height;y++)for(int x=0;x<b.Width;x++){int xx=r.X+x*k+(name=="crane_hook"?8:k/2),yy=r.Y+y*k+k/2;Color c=xx<r.Right&&yy<r.Bottom?s.GetPixel(xx,yy):Color.Transparent;b.SetPixel(x,y,c.A>=128?p[Near(c)]:Color.FromArgb(0,0,0,0));}report.Add(name+": source="+s.Width+"x"+s.Height+", alpha bbox="+r+", whole-sprite integer divisor="+k+", native canvas="+b.Width+"x"+b.Height+", visible="+Bounds(b));return b;}}
 static Bitmap Off(Bitmap b){var c=New(b.Width,b.Height);for(int y=0;y<b.Height;y++)for(int x=0;x<b.Width;x++){Color v=b.GetPixel(x,y);c.SetPixel(x,y,Cyan(v)?p[3]:v);}return c;}
 static void Cell(Bitmap atlas,Bitmap b,int col,int row,int size){int x=col*size+(size-b.Width)/2;int y=row*size+(int)Math.Round(size*.88)-Bounds(b).Bottom;Put(atlas,b,x,y);report.Add("atlas "+atlas.Width+"x"+atlas.Height+" cell="+col+","+row+" origin="+x+","+y+" feet baseline="+((row*size)+(int)Math.Round(size*.88)));}
 static void Ground(Bitmap d,Bitmap s,int x,int baseline){Put(d,s,x,baseline-Bounds(s).Bottom);}
 public static void Run(string dir){root=dir;string[] hex={"#0b0c0d","#15181a","#1f2427","#2c3236","#3d4448","#566064","#737d82","#98a2a6","#c3cacc","#a9b2b3","#d4dadb","#eef2f2","#6b5a1e","#b89a2a","#f4d73c","#6e2f14","#b8531f","#e0782a","#0f3a40","#2a8a92","#5fd0d8","#b8f4f6","#5a4428","#c89a5a","#f1d9a6","#8a1f1f"};p=Array.ConvertAll(hex,ColorTranslator.FromHtml);
  var bench=Reduce("workbench",24);var cabinet=Reduce("weapon_cabinet",28);var hook=Reduce("crane_hook",30);var arm=Reduce("robotic_arm",26);var single=Reduce("crate_single",48);var stack=Reduce("crate_stack",30);
  Save("rhodes_workbench_on_v1",bench);Save("rhodes_workbench_off_v1",Off(bench));Save("rhodes_weapon_cabinet_on_v1",cabinet);Save("rhodes_weapon_cabinet_off_v1",Off(cabinet));Save("rhodes_crane_hook_v1",hook);Save("rhodes_robotic_arm_on_v1",arm);Save("rhodes_robotic_arm_off_v1",Off(arm));Save("rhodes_supply_crate_v1",single);Save("rhodes_supply_crates_stack_v1",stack);
  var stations=New(512,256);Cell(stations,bench,0,0,128);Cell(stations,cabinet,1,0,128);Cell(stations,a["rhodes_workbench_off_v1"],0,1,128);Cell(stations,a["rhodes_weapon_cabinet_off_v1"],1,1,128);Save("rhodes_equipment_stations_v1",stations);
  var props=New(256,192);Cell(props,single,0,0,64);Cell(props,stack,1,0,64);Cell(props,hook,2,0,64);Cell(props,arm,3,0,64);Cell(props,a["rhodes_robotic_arm_off_v1"],3,1,64);Save("rhodes_equipment_props_v1",props);
  using(var floor=new Bitmap(Path.Combine(root,"../rhodes_floor_v1.png")))using(var wall=new Bitmap(Path.Combine(root,"../batch1_v5/wall_straight_60x46_v5.png")))using(var side=new Bitmap(Path.Combine(root,"../batch1_v5/wall_top_6_plus2_v5.png")))using(var shadow=new Bitmap(Path.Combine(root,"../batch1_v5/wall_floor_contact_shadow_60x2_v5.png")))using(var sheet=new Bitmap(Path.GetFullPath(Path.Combine(root,"../../../godot_assets/lappland_combat_64.png"))))using(var ch=sheet.Clone(new Rectangle(0,0,64,64),PixelFormat.Format32bppArgb)){
   var room=New(196,169);for(int y=0;y<room.Height;y++)for(int x=0;x<room.Width;x++)room.SetPixel(x,y,x>=8&&x<188&&y>=46&&y<161?floor.GetPixel((x-8)%120,(y-46)%120):p[1]);for(int x=8;x<188;x+=60){Put(room,wall,x,0);Put(room,shadow,x,46);}for(int y=46;y<161;y+=60){Put(room,side,0,y);Put(room,side,188,y);}using(var cl=new Bitmap(Path.Combine(root,"../batch1_v5/corner_left_L_v5.png")))using(var cr=new Bitmap(Path.Combine(root,"../batch1_v5/corner_right_L_v5.png"))){Put(room,cl,0,0);Put(room,cr,164,0);}Ground(room,bench,19,74);Ground(room,cabinet,151,74);Put(room,hook,106,3);Ground(room,arm,126,122);Ground(room,stack,21,144);Ground(room,single,68,145);Ground(room,ch,78-Bounds(ch).Left,122);room.Save(Path.Combine(root,"equipment_bay_lappland_1x.png"));Up(room,"equipment_bay_lappland_4x",4);
   var review=New(480,150);for(int y=0;y<review.Height;y++)for(int x=0;x<review.Width;x++)review.SetPixel(x,y,floor.GetPixel(x%120,y%120));for(int x=0;x<480;x+=60)Put(review,wall,x,4);Ground(review,bench,8,76);Ground(review,ch,86-Bounds(ch).Left,76);Ground(review,cabinet,144,76);Ground(review,ch,182-Bounds(ch).Left,76);Put(review,hook,240,8);Ground(review,ch,283-Bounds(ch).Left,76);Ground(review,arm,343,76);Ground(review,ch,395-Bounds(ch).Left,76);Ground(review,stack,20,140);Ground(review,single,69,140);Ground(review,ch,104-Bounds(ch).Left,140);Ground(review,a["rhodes_workbench_off_v1"],172,140);Ground(review,a["rhodes_weapon_cabinet_off_v1"],275,140);Ground(review,a["rhodes_robotic_arm_off_v1"],345,140);review.Save(Path.Combine(root,"equipment_scale_review_1x.png"));Up(review,"equipment_scale_review_4x",4);
   report.Add("PASS static room composite196x169 (interior180x115), scale review480x150, both exact4x. Lappland frame0 copied at1:1, actual alpha>=128 height="+Bounds(ch).Height+". Composite retains character original colors.");
  }
  foreach(var kv in a){var b=kv.Value;var colors=new HashSet<int>();int cyan=0;using(var big=new Bitmap(Path.Combine(root,kv.Key+"_8x.png"))){Check(big.Width==b.Width*8&&big.Height==b.Height*8,"8x size");for(int y=0;y<b.Height;y++)for(int x=0;x<b.Width;x++){var c=b.GetPixel(x,y);Check(c.A==0||c.A==255,"binary alpha");if(c.A==255){Check(p[Near(c)].ToArgb()==c.ToArgb(),"palette");colors.Add(c.ToArgb());if(Cyan(c))cyan++;}for(int j=0;j<8;j++)for(int i=0;i<8;i++)Check(big.GetPixel(x*8+i,y*8+j).ToArgb()==c.ToArgb(),"8x blocks");}}if(kv.Key.Contains("_off_"))Check(cyan==0,"OFF cyan");report.Add("PASS "+kv.Key+": "+b.Width+"x"+b.Height+", colors="+colors.Count+", cyan="+cyan+", binary alpha, palette and exact8x");}
  foreach(string s in new[]{"workbench","weapon_cabinet","robotic_arm"}){var on=a["rhodes_"+s+"_on_v1"];var off=a["rhodes_"+s+"_off_v1"];for(int y=0;y<on.Height;y++)for(int x=0;x<on.Width;x++)Check(on.GetPixel(x,y).A==off.GetPixel(x,y).A,"ON/OFF alpha");}
  Check(bench.Height<=50&&cabinet.Height<=46&&arm.Height<=50,"prop heights");report.Add("Workbench whole-source surface starts around y470; feet end805. /24 gives14px surface-to-ground; no section scaling. Monitor/lamp sit on surface.");report.Add("Crane atlas baseline aligns hook tip ONLY; scene pivot is rail top midpoint, suspended with tip above floor. Empty slots intentional. NOT RUN: engine integration; visual acceptance pending.");File.WriteAllText(Path.Combine(root,"validation.txt"),string.Join("\n",report)+"\n");
 }
}
'@
Add-Type -TypeDefinition $code -ReferencedAssemblies System.Drawing
[EquipmentV1]::Run($PSScriptRoot)
Get-Content -LiteralPath (Join-Path $PSScriptRoot 'validation.txt')


